#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $DB_USER WITH PASSWORD '$DB_PASSWORD';
    CREATE DATABASE $DB_NAME;
    GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_USER;
    ALTER ROLE $DB_USER WITH CREATEDB;

    START TRANSACTION;
    CREATE TABLE "CategoryChannelAlerts" (
        alert_id integer GENERATED BY DEFAULT AS IDENTITY,
        channel_id numeric(20,0) NOT NULL,
        category_id text NOT NULL,
        CONSTRAINT "PK_CategoryChannelAlerts" PRIMARY KEY (alert_id)
    );
    CREATE TABLE "ChannelQuestionAlerts" (
        alert_id integer GENERATED BY DEFAULT AS IDENTITY,
        channel_id numeric(20,0) NOT NULL,
        question_id bigint NOT NULL,
        CONSTRAINT "PK_ChannelQuestionAlerts" PRIMARY KEY (alert_id)
    );
    CREATE TABLE "UserQuestionAlerts" (
        alert_id integer GENERATED BY DEFAULT AS IDENTITY,
        user_id numeric(20,0) NOT NULL,
        question_id bigint NOT NULL,
        CONSTRAINT "PK_UserQuestionAlerts" PRIMARY KEY (alert_id)
    );

    COMMIT;
EOSQL